// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/auth/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/img21326/fb_chat/structure/user"
)

// MockAuthUsecaseInterFace is a mock of AuthUsecaseInterFace interface.
type MockAuthUsecaseInterFace struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseInterFaceMockRecorder
}

// MockAuthUsecaseInterFaceMockRecorder is the mock recorder for MockAuthUsecaseInterFace.
type MockAuthUsecaseInterFaceMockRecorder struct {
	mock *MockAuthUsecaseInterFace
}

// NewMockAuthUsecaseInterFace creates a new mock instance.
func NewMockAuthUsecaseInterFace(ctrl *gomock.Controller) *MockAuthUsecaseInterFace {
	mock := &MockAuthUsecaseInterFace{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseInterFaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecaseInterFace) EXPECT() *MockAuthUsecaseInterFaceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockAuthUsecaseInterFace) GenerateToken(ctx context.Context, user *user.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthUsecaseInterFaceMockRecorder) GenerateToken(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuthUsecaseInterFace)(nil).GenerateToken), ctx, user)
}

// VerifyToken mocks base method.
func (m *MockAuthUsecaseInterFace) VerifyToken(token string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", token)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthUsecaseInterFaceMockRecorder) VerifyToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthUsecaseInterFace)(nil).VerifyToken), token)
}
