version: '3.1'

services:
  server:
    build: .
    image: chat_server
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./backup/pgdata:/var/lib/postgresql/data/pgdata
